# Generated by Django 3.2 on 2021-05-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.RemoveField(
            model_name='root',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='idUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nroCompra',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='nroDevolucion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISSN',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nroNoticia',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nroReserva',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='root',
            name='idUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nroTarjeta',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
