# Generated by Django 3.2 on 2021-06-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20210524_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
