# Generated by Django 3.2 on 2021-06-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(default='apellido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(default='correo@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(default='direccion', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='dni',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='fechaN',
            field=models.DateField(default='23/3/1999'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='genero',
            field=models.CharField(default='M', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='lugarN',
            field=models.CharField(default='pereira', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombres',
            field=models.CharField(default='nombre', max_length=20),
            preserve_default=False,
        ),
    ]
