# Generated by Django 3.2 on 2021-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20210616_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='escritor',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='anho',
        ),
        migrations.AddField(
            model_name='libro',
            name='caratula',
            field=models.ImageField(null=True, upload_to='caratulas'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='fechaLanzamiento',
            field=models.DateField(default='1999-09-07'),
            preserve_default=False,
        ),
    ]
