# Generated by Django 3.2 on 2021-06-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20210616_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='ISSN',
            new_name='issn',
        ),
    ]
